// Conciliação v9: OFX = fato bancário. Concilia somente com pagamentos/recebimentos registrados.
const KREC='aritech_hml_receipts_v1';
let REC=JSON.parse(localStorage.getItem(KREC)||'[]');
function saveReceipts(){localStorage.setItem(KREC,JSON.stringify(REC))}
function txValue(t){return Math.abs(Number(t.amount||0))}
function cashEventAvailable(x){return x&&x.status!=='RECONCILED'&&!x.bankTransactionId}
function paymentCashAmount(p){return Number(p.amount??p.principal??0)}
function receiptCashAmount(r){return Number(r.amount||0)}
function paymentLabel(p){return (p.beneficiary||'Pagamento')+' · '+(p.description||p.reference||'sem descrição')}
function receiptLabel(r){return (r.customerName||'Cliente')+' · '+(r.description||r.reference||'sem descrição')}
function exactCash(a,b){return Math.abs(Number(a||0)-Number(b||0))<0.011}
function eventDate(x){return String(x.date||x.receivedAt||x.due||'')}
function candidateForTxV9(t){
  const d=ofxDate(t.date),v=txValue(t),isDebit=Number(t.amount||0)<0;
  const list=isDebit?PM.filter(cashEventAvailable).map(x=>({kind:'PAYMENT',event:x,label:paymentLabel(x),value:paymentCashAmount(x),date:eventDate(x)})):REC.filter(cashEventAvailable).map(x=>({kind:'RECEIPT',event:x,label:receiptLabel(x),value:receiptCashAmount(x),date:eventDate(x)}));
  return list.filter(x=>exactCash(x.value,v)).map(x=>({...x,score:daysBetween(d,x.date)})).filter(x=>x.score<=15).sort((a,b)=>a.score-b.score)[0]||null;
}
function manualEventsV9(t){
  if(Number(t.amount||0)<0)return PM.filter(cashEventAvailable).map(p=>({kind:'PAYMENT',id:p.id,label:paymentLabel(p)+' · '+money(paymentCashAmount(p))+' · '+(p.date||'sem data')}));
  return REC.filter(cashEventAvailable).map(r=>({kind:'RECEIPT',id:r.id,label:receiptLabel(r)+' · '+money(receiptCashAmount(r))+' · '+(r.date||'sem data')}));
}
function linkCashEventV9(t,kind,event){
  if(!t||!event)return;
  const expected=kind==='PAYMENT'?paymentCashAmount(event):receiptCashAmount(event),actual=txValue(t);
  if(!exactCash(expected,actual))return alert('O valor do evento registrado ('+money(expected)+') é diferente do valor realizado no OFX ('+money(actual)+'). Ajuste ou registre o evento correto antes de conciliar.');
  event.status='RECONCILED';event.bankTransactionId=t.id;event.reconciledAt=new Date().toISOString();
  t.status='RECONCILED';t.reconciledAt=new Date().toISOString();t.cashEventType=kind;t.cashEventId=event.id;
  if(kind==='PAYMENT')t.paymentId=event.id;else t.receiptId=event.id;
  save();saveReceipts();render();
}
function confirmAutoV9(txid){const t=R.find(x=>x.id===txid);if(!t||t.status==='RECONCILED')return;const c=candidateForTxV9(t);if(!c)return alert('Nenhum pagamento/recebimento registrado corresponde automaticamente a esta operação. Use o vínculo manual ou classifique a operação do OFX.');linkCashEventV9(t,c.kind,c.event)}
window.confirmSmartRec=confirmAutoV9;
function manualReconcileV9(txid,value){const t=R.find(x=>x.id===txid);if(!t||t.status==='RECONCILED')return;const [kind,id]=String(value||'').split(':');if(kind==='PAYMENT'){const p=PM.find(x=>x.id===id);if(!p)return alert('Pagamento não encontrado.');return linkCashEventV9(t,kind,p)}if(kind==='RECEIPT'){const r=REC.find(x=>x.id===id);if(!r)return alert('Recebimento não encontrado.');return linkCashEventV9(t,kind,r)}alert('Selecione um pagamento ou recebimento registrado.')}
window.manualReconcile=manualReconcileV9;
function applyPaymentToPayableV9(p,value){if(!p)return;let remaining=value;const its=(p.installments||[]).filter(i=>Number(i.open)>0).sort((a,b)=>String(a.due||'').localeCompare(String(b.due||''))||Number(a.sequence||0)-Number(b.sequence||0));for(const i of its){if(remaining<=0.001)break;const part=Math.min(remaining,Number(i.open));i.open=+(Number(i.open)-part).toFixed(2);i.status=i.open<=0.001?'SETTLED':'PARTIALLY_SETTLED';remaining=+(remaining-part).toFixed(2)}const all=(p.installments||[]).every(i=>Number(i.open)<=0.001),any=(p.installments||[]).some(i=>Number(i.open)<Number(i.original));p.status=all?'SETTLED':any?'PARTIALLY_SETTLED':'OPEN'}
function applyReceiptToReceivableV9(r,value){if(!r)return;r.receivedAmount=+(Number(r.receivedAmount||0)+value).toFixed(2);r.status=arOpen(r)<=0.011?'RECEIVED':'PARTIALLY_RECEIVED';r.receivedAt=new Date().toISOString().slice(0,10)}
let openClassifyTxV9=null;
function toggleClassifyV9(txid){openClassifyTxV9=openClassifyTxV9===txid?null:txid;renderReconciliationV9()}
window.toggleClassifyV9=toggleClassifyV9;
function paymentClassificationOptionsV9(){return '<option value="">Sem conta a pagar prévia</option>'+P.filter(p=>['APPROVED','OPEN','PARTIALLY_SETTLED'].includes(p.status)&&(p.installments||[]).some(i=>Number(i.open)>0)).map(p=>'<option value="'+p.id+'">'+esc(p.beneficiary+' · '+p.description+' · saldo '+money((p.installments||[]).reduce((s,i)=>s+Number(i.open||0),0)))+'</option>').join('')}
function receivableClassificationOptionsV9(){return '<option value="">Sem conta a receber prévia</option>'+AR.filter(r=>arOpen(r)>0).map(r=>'<option value="'+r.id+'">'+esc((r.customerName||'Cliente')+' · '+r.description+' · saldo '+money(arOpen(r)))+'</option>').join('')}
function beneficiaryOptionsV9(){return '<option value="">Selecione</option><optgroup label="Fornecedores">'+S.map(x=>'<option value="SUPPLIER:'+x.id+'">'+esc(sn(x))+'</option>').join('')+'</optgroup><optgroup label="Colaboradores">'+E.map(x=>'<option value="EMPLOYEE:'+x.id+'">'+esc(x.name)+'</option>').join('')+'</optgroup>'}
function customerOptionsV9(){return '<option value="">Selecione</option>'+CUS.map(c=>'<option value="'+c.id+'">'+esc(customerName(c))+'</option>').join('')}
function classifyFormV9(t){const debit=Number(t.amount||0)<0,id=esc(t.id),d=ofxDate(t.date),v=money(txValue(t));if(debit)return '<div class="quick" style="margin-top:10px"><div class="quickTitle">Registrar saída realizada a partir do OFX</div><div class="grid"><label class="field">Conta a pagar relacionada<select id="v9-payable-'+id+'">'+paymentClassificationOptionsV9()+'</select></label><label class="field">Beneficiário<select id="v9-beneficiary-'+id+'">'+beneficiaryOptionsV9()+'</select></label><label class="field full">Descrição<input id="v9-desc-'+id+'" value="'+esc(t.memo||'Movimentação bancária')+'"></label><label class="field">Conta gerencial<select id="v9-mgmt-'+id+'"><option value="">Selecione</option>'+mgmt.map(x=>'<option>'+esc(x)+'</option>').join('')+'</select></label><label class="field">Centro de custo<select id="v9-cc-'+id+'"><option value="">Selecione</option>'+cc.map(x=>'<option>'+esc(x)+'</option>').join('')+'</select></label><label class="field">Data realizada<input value="'+d+'" disabled></label><label class="field">Valor<input value="'+v+'" disabled></label></div><div class="quickActions"><button class="btn" onclick="toggleClassifyV9(\''+t.id+'\')">Cancelar</button><button class="btn primary" onclick="saveClassifiedOfxV9(\''+t.id+'\')">Registrar e conciliar</button></div></div>';
return '<div class="quick" style="margin-top:10px"><div class="quickTitle">Registrar entrada realizada a partir do OFX</div><div class="grid"><label class="field">Conta a receber relacionada<select id="v9-ar-'+id+'">'+receivableClassificationOptionsV9()+'</select></label><label class="field">Cliente<select id="v9-customer-'+id+'">'+customerOptionsV9()+'</select></label><label class="field full">Descrição<input id="v9-desc-'+id+'" value="'+esc(t.memo||'Movimentação bancária')+'"></label><label class="field">Origem<select id="v9-origin-'+id+'"><option>Medição</option><option>Nota fiscal</option><option>Contrato</option><option>Venda</option><option>Outro</option></select></label><label class="field">Data realizada<input value="'+d+'" disabled></label><label class="field">Valor<input value="'+v+'" disabled></label></div><div class="quickActions"><button class="btn" onclick="toggleClassifyV9(\''+t.id+'\')">Cancelar</button><button class="btn primary" onclick="saveClassifiedOfxV9(\''+t.id+'\')">Registrar e conciliar</button></div></div>'}
function saveClassifiedOfxV9(txid){
  const t=R.find(x=>x.id===txid);if(!t||t.status==='RECONCILED')return;const value=txValue(t),date=ofxDate(t.date),desc=(document.getElementById('v9-desc-'+txid)||{}).value?.trim()||t.memo||'Movimentação bancária';
  if(Number(t.amount||0)<0){
    const payableId=document.getElementById('v9-payable-'+txid).value,cp=document.getElementById('v9-beneficiary-'+txid).value,management=document.getElementById('v9-mgmt-'+txid).value,costCenter=document.getElementById('v9-cc-'+txid).value;
    let payable=payableId?P.find(x=>x.id===payableId):null;let beneficiary='';let counterpartyId='',counterpartyType='';
    if(payable){beneficiary=payable.beneficiary;counterpartyId=payable.counterpartyId;counterpartyType=payable.counterpartyType;const open=(payable.installments||[]).reduce((s,i)=>s+Number(i.open||0),0);if(value>open+0.011)return alert('O valor realizado é maior que o saldo da Conta a Pagar escolhida. Selecione outra conta ou registre como operação sem programação prévia.');applyPaymentToPayableV9(payable,value)}
    else{if(!cp||!management||!costCenter)return alert('Para uma saída sem Conta a Pagar prévia, informe beneficiário, conta gerencial e centro de custo.');[counterpartyType,counterpartyId]=cp.split(':');const obj=counterpartyType==='EMPLOYEE'?E.find(x=>x.id===counterpartyId):S.find(x=>x.id===counterpartyId);beneficiary=counterpartyType==='EMPLOYEE'?(obj?.name||'Colaborador'):(obj?sn(obj):'Fornecedor');payable={id:crypto.randomUUID(),counterpartyId,counterpartyType,beneficiary,obligation:'Movimentação realizada via OFX',description:desc,amount:value,issue:date,competence:date.slice(0,7),status:'SETTLED',directness:'INDIRECT',management,cc:costCenter,business:'',project:'',installments:[{id:crypto.randomUUID(),sequence:1,due:date,original:value,open:0,status:'SETTLED'}],createdFromOfx:true};P.push(payable)}
    const payment={id:crypto.randomUUID(),payableId:payable.id,beneficiary,description:desc,date,account:'OFX',method:'Movimentação bancária',principal:value,interest:0,penalty:0,discount:0,amount:value,reference:t.memo||t.id,status:'RECONCILED',bankTransactionId:t.id,createdFromOfx:true};PM.push(payment);t.status='RECONCILED';t.paymentId=payment.id;t.cashEventType='PAYMENT';t.cashEventId=payment.id;t.reconciledAt=new Date().toISOString();save();openClassifyTxV9=null;render();return;
  }
  const arId=document.getElementById('v9-ar-'+txid).value,customerId=document.getElementById('v9-customer-'+txid).value,origin=document.getElementById('v9-origin-'+txid).value;let ar=arId?AR.find(x=>x.id===arId):null;let customerNameValue='';
  if(ar){customerNameValue=ar.customerName||'Cliente';const open=arOpen(ar);if(value>open+0.011)return alert('O valor realizado é maior que o saldo da Conta a Receber escolhida. Selecione outra conta ou registre como operação sem programação prévia.');applyReceiptToReceivableV9(ar,value)}
  else{const c=CUS.find(x=>x.id===customerId);if(!c)return alert('Para uma entrada sem Conta a Receber prévia, selecione o cliente.');customerNameValue=customerName(c);ar={id:crypto.randomUUID(),customerId:c.id,customerName:customerNameValue,contractId:'',projectId:'',origin,description:desc,document:'',amount:value,receivedAmount:value,issue:date,due:date,level:'COMMITTED',status:'RECEIVED',receivedAt:date,createdFromOfx:true};AR.push(ar)}
  const receipt={id:crypto.randomUUID(),receivableId:ar.id,customerId:ar.customerId||customerId,customerName:customerNameValue,description:desc,date,amount:value,reference:t.memo||t.id,status:'RECONCILED',bankTransactionId:t.id,createdFromOfx:true};REC.push(receipt);t.status='RECONCILED';t.receiptId=receipt.id;t.cashEventType='RECEIPT';t.cashEventId=receipt.id;t.reconciledAt=new Date().toISOString();saveAR();saveReceipts();save();openClassifyTxV9=null;render();
}
window.saveClassifiedOfxV9=saveClassifiedOfxV9;
function ensureReceiptPanelV9(){const section=document.getElementById('receivables');if(!section||document.getElementById('receiptPanelV9'))return;const panel=document.createElement('div');panel.className='panel';panel.id='receiptPanelV9';panel.innerHTML='<h2>Registrar recebimento</h2><div class="grid"><label class="field full">Conta a receber<select id="v9-receipt-ar"></select></label><label class="field">Data<input id="v9-receipt-date" type="date"></label><label class="field">Valor (R$)<input id="v9-receipt-amount" inputmode="numeric"></label><label class="field full">Referência<input id="v9-receipt-ref"></label></div><div class="actions"><button class="btn primary" id="v9-receipt-save">Registrar recebimento</button></div><div id="v9-receipt-list" style="margin-top:14px"></div>';section.appendChild(panel);document.getElementById('v9-receipt-date').value=today;document.getElementById('v9-receipt-amount').oninput=e=>e.target.value=moneyMask(e.target.value);document.getElementById('v9-receipt-save').onclick=registerReceiptV9}
function refreshReceiptPanelV9(){ensureReceiptPanelV9();const s=document.getElementById('v9-receipt-ar');if(!s)return;const old=s.value;s.innerHTML='<option value="">Selecione</option>'+AR.filter(r=>arOpen(r)>0).map(r=>'<option value="'+r.id+'">'+esc((r.customerName||'Cliente')+' · '+r.description+' · saldo '+money(arOpen(r)))+'</option>').join('');if(AR.some(r=>r.id===old&&arOpen(r)>0))s.value=old;const list=document.getElementById('v9-receipt-list');list.innerHTML=REC.length?'<table class="table"><tr><th>Data</th><th>Cliente</th><th>Descrição</th><th>Valor</th><th>Status</th></tr>'+REC.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(r=>'<tr><td>'+esc(r.date)+'</td><td>'+esc(r.customerName||'')+'</td><td>'+esc(r.description||'')+'</td><td>'+money(r.amount)+'</td><td>'+esc(r.status)+'</td></tr>').join('')+'</table>':'<div class="muted">Nenhum recebimento registrado.</div>'}
function registerReceiptV9(){const ar=AR.find(x=>x.id===document.getElementById('v9-receipt-ar').value),date=document.getElementById('v9-receipt-date').value,value=moneyNum(document.getElementById('v9-receipt-amount').value),ref=document.getElementById('v9-receipt-ref').value.trim();if(!ar||!date||value<=0)return alert('Informe Conta a Receber, data e valor.');if(value>arOpen(ar)+0.011)return alert('O recebimento não pode superar o saldo da Conta a Receber.');applyReceiptToReceivableV9(ar,value);REC.push({id:crypto.randomUUID(),receivableId:ar.id,customerId:ar.customerId,customerName:ar.customerName||'Cliente',description:ar.description,date,amount:value,reference:ref,status:'CONFIRMED'});saveAR();saveReceipts();render();document.getElementById('v9-receipt-amount').value='';document.getElementById('v9-receipt-ref').value=''}
function renderReconciliationV9(){const el=document.getElementById('recList');if(!el)return;el.innerHTML=R.length?'<table class="table"><tr><th>Data</th><th>Descrição bancária</th><th>Valor realizado</th><th>Conciliação</th></tr>'+R.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(t=>{if(t.status==='RECONCILED'){let ref='';if(t.cashEventType==='PAYMENT'||t.paymentId){const p=PM.find(x=>x.id===(t.cashEventId||t.paymentId));if(p)ref=paymentLabel(p)}else{const r=REC.find(x=>x.id===(t.cashEventId||t.receiptId));if(r)ref=receiptLabel(r)}return '<tr><td>'+esc(ofxDate(t.date))+'</td><td>'+esc(t.memo)+'</td><td>'+money(t.amount)+'</td><td><span class="valid">Conciliado</span>'+(ref?'<div class="muted">'+esc(ref)+'</div>':'')+'</td></tr>'}const c=candidateForTxV9(t),opts=manualEventsV9(t),sel='<select id="manual-'+esc(t.id)+'"><option value="">Selecionar pagamento/recebimento...</option>'+opts.map(o=>'<option value="'+o.kind+':'+o.id+'">'+esc(o.label)+'</option>').join('')+'</select>',auto=c?'<button class="btn success" onclick="confirmSmartRec(\''+t.id+'\')">Confirmar match</button><div class="muted">'+esc(c.label)+' · '+money(c.value)+'</div>':'<span class="muted">Sem match automático</span>',form=openClassifyTxV9===t.id?classifyFormV9(t):'';return '<tr><td>'+esc(ofxDate(t.date))+'</td><td>'+esc(t.memo)+'</td><td>'+money(t.amount)+'</td><td>'+auto+'<div style="margin-top:10px" class="rowActions">'+sel+'<button class="btn" onclick="manualReconcile(\''+t.id+'\',document.getElementById(\'manual-'+t.id+'\').value)">Vincular manualmente</button><button class="btn primary" onclick="toggleClassifyV9(\''+t.id+'\')">Classificar operação</button></div>'+form+'</td></tr>'}).join('')+'</table>':'<div class="muted">Nenhuma operação importada por OFX.</div>'}
const renderBeforeV9=render;render=function(){renderBeforeV9();refreshReceiptPanelV9();renderReconciliationV9()};renderSmartRec=renderReconciliationV9;window.__ARITECH_RECONCILIATION_V9__=true;render();