'use client';

import { useState } from 'react';

type Payable={id:string;description:string;originalAmount:string;competenceDate:string;status:string;counterpartyType:string};
const apiBase=process.env.NEXT_PUBLIC_API_URL?`${process.env.NEXT_PUBLIC_API_URL}/api`:'http://localhost:3001/api';
const money=(v:string)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v));

export default function ApprovalsPage(){
  const [legalEntityId,setLegalEntityId]=useState('');const[actorId,setActorId]=useState('');const[items,setItems]=useState<Payable[]>([]);const[msg,setMsg]=useState('');const[err,setErr]=useState('');const[reason,setReason]=useState<Record<string,string>>({});
  async function api<T>(p:string,i?:RequestInit){const r=await fetch(`${apiBase}${p}`,{...i,headers:{'Content-Type':'application/json'}});const t=await r.text(),b=t?JSON.parse(t):null;if(!r.ok)throw new Error(b?.message||'Falha na API');return b as T}
  async function load(){setErr('');try{const all=await api<Payable[]>(`/financial/payables?legalEntityId=${legalEntityId}`);setItems(all.filter(x=>x.status==='PENDING_APPROVAL'))}catch(e){setErr(e instanceof Error?e.message:'Erro ao carregar')}}
  async function decide(id:string,kind:'approve'|'reject'){setErr('');setMsg('');if(kind==='reject'&&!reason[id]?.trim())return setErr('Informe a justificativa da reprovação.');try{await api(`/financial/payables/${id}/approvals/${kind}`,{method:'POST',body:JSON.stringify({actorId,reason:reason[id]||undefined})});setMsg(kind==='approve'?'Conta aprovada.':'Conta reprovada e devolvida para ajuste.');await load()}catch(e){setErr(e instanceof Error?e.message:'Erro na aprovação')}}
  return <main><header><div><small>Financeiro</small><h1>Aprovações</h1><p>Autorize ou devolva contas a pagar antes da liquidação.</p></div><a href="/">← Workspace</a></header><section className="config"><label>Legal Entity ID<input value={legalEntityId} onChange={e=>setLegalEntityId(e.target.value)}/></label><label>Actor/User ID<input value={actorId} onChange={e=>setActorId(e.target.value)}/></label><button onClick={load}>Atualizar pendências</button></section>{err&&<div className="error">{err}</div>}{msg&&<div className="success">{msg}</div>}<section className="panel">{items.length?items.map(p=><article key={p.id}><div><b>{p.description}</b><span>{p.counterpartyType==='EMPLOYEE'?'Colaborador':'Fornecedor'} · {new Date(p.competenceDate).toLocaleDateString('pt-BR')} · <strong>{money(p.originalAmount)}</strong></span></div><textarea placeholder="Justificativa (obrigatória para reprovar)" value={reason[p.id]||''} onChange={e=>setReason({...reason,[p.id]:e.target.value})}/><div className="actions"><button className="approve" onClick={()=>decide(p.id,'approve')}>Aprovar</button><button className="reject" onClick={()=>decide(p.id,'reject')}>Reprovar</button></div></article>):<div className="empty">Nenhuma conta aguardando aprovação.</div>}</section><style jsx>{`main{max-width:1050px;margin:auto;padding:32px 20px;color:#172033}header{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:24px}h1{font-size:32px;margin:4px 0}p,span{color:#64748b}a{font-weight:700;color:#334155;text-decoration:none}.config,.panel{background:#fff;border:1px solid #e2e8f0;border-radius:14px;padding:18px}.config{display:grid;grid-template-columns:1fr 1fr auto;gap:12px;align-items:end;margin-bottom:16px}.config label{display:flex;flex-direction:column;gap:6px;font-size:12px;font-weight:700}input,textarea,button{border:1px solid #cbd5e1;border-radius:9px;padding:10px 12px;font:inherit;background:#fff;min-height:42px}button{font-weight:800;cursor:pointer}article{display:grid;grid-template-columns:1.3fr 1fr auto;gap:14px;align-items:center;padding:14px 0;border-bottom:1px solid #edf2f7}article>div:first-child{display:flex;flex-direction:column;gap:4px}.actions{display:flex;gap:8px}.approve{background:#172033;color:#fff}.reject{color:#b91c1c;border-color:#fecaca}.error,.success{padding:12px;border-radius:9px;margin-bottom:12px}.error{background:#fef2f2;color:#991b1b}.success{background:#f0fdf4;color:#166534}.empty{color:#64748b;padding:20px}@media(max-width:760px){.config,article{grid-template-columns:1fr}.actions{justify-content:flex-end}}`}</style></main>
}
