/**
 * Códigos de erro de domínio — catálogo estável usado pela API e pela UI.
 * Fontes: FINANCIAL_MODEL.md §52, ADR-008 §85, ADR-009 §89.
 */
export const DOMAIN_ERROR_CODES = {
  // Financeiro geral
  FINANCIAL_PERIOD_CLOSED: "FINANCIAL_PERIOD_CLOSED",
  FINANCIAL_PERIOD_CLOSING: "FINANCIAL_PERIOD_CLOSING",
  FINANCIAL_PERIOD_ALREADY_CLOSED: "FINANCIAL_PERIOD_ALREADY_CLOSED",
  FINANCIAL_PERIOD_HAS_BLOCKING_ISSUES: "FINANCIAL_PERIOD_HAS_BLOCKING_ISSUES",
  FINANCIAL_PERIOD_REOPEN_PERMISSION_REQUIRED: "FINANCIAL_PERIOD_REOPEN_PERMISSION_REQUIRED",
  CURRENCY_MISMATCH: "CURRENCY_MISMATCH",

  // Contas a pagar / receber
  PAYABLE_ALREADY_SETTLED: "PAYABLE_ALREADY_SETTLED",
  PAYABLE_HAS_PAYMENTS: "PAYABLE_HAS_PAYMENTS",
  PAYABLE_NOT_APPROVED: "PAYABLE_NOT_APPROVED",
  RECEIVABLE_ALREADY_SETTLED: "RECEIVABLE_ALREADY_SETTLED",
  INSTALLMENT_AMOUNT_EXCEEDED: "INSTALLMENT_AMOUNT_EXCEEDED",
  MANAGEMENT_ACCOUNT_NOT_POSTABLE: "MANAGEMENT_ACCOUNT_NOT_POSTABLE",
  APPROVAL_REQUIRED: "APPROVAL_REQUIRED",
  APPROVAL_LIMIT_EXCEEDED: "APPROVAL_LIMIT_EXCEEDED",
  ADVANCE_BALANCE_EXCEEDED: "ADVANCE_BALANCE_EXCEEDED",

  // Contratos / alocação de custos e receitas
  CONTRACT_REQUIRED_FOR_PRODUCTION: "CONTRACT_REQUIRED_FOR_PRODUCTION",
  CONTRACT_REQUIRED_FOR_RECEIVABLE: "CONTRACT_REQUIRED_FOR_RECEIVABLE",
  CONTRACT_NOT_ACTIVE: "CONTRACT_NOT_ACTIVE",
  CONTRACT_INCOMPLETE: "CONTRACT_INCOMPLETE",
  CONTRACT_CUSTOMER_MISMATCH: "CONTRACT_CUSTOMER_MISMATCH",
  COST_CENTER_CONTRACT_MISMATCH: "COST_CENTER_CONTRACT_MISMATCH",
  PROJECT_CONTRACT_MISMATCH: "PROJECT_CONTRACT_MISMATCH",
  PAYABLE_NOT_EDITABLE: "PAYABLE_NOT_EDITABLE",

  // Pagamentos / recebimentos
  PAYMENT_ALREADY_RECONCILED: "PAYMENT_ALREADY_RECONCILED",
  RECEIPT_ALREADY_RECONCILED: "RECEIPT_ALREADY_RECONCILED",
  TRANSFER_ACCOUNTS_MUST_DIFFER: "TRANSFER_ACCOUNTS_MUST_DIFFER",

  // Banco / conciliação
  BANK_STATEMENT_DUPLICATE: "BANK_STATEMENT_DUPLICATE",
  BANK_STATEMENT_INVALID_FORMAT: "BANK_STATEMENT_INVALID_FORMAT",
  BANK_STATEMENT_ACCOUNT_MISMATCH: "BANK_STATEMENT_ACCOUNT_MISMATCH",
  BANK_TRANSACTION_DUPLICATE: "BANK_TRANSACTION_DUPLICATE",
  BANK_TRANSACTION_ALREADY_MATCHED: "BANK_TRANSACTION_ALREADY_MATCHED",
  BANK_TRANSACTION_MATCH_AMOUNT_EXCEEDED: "BANK_TRANSACTION_MATCH_AMOUNT_EXCEEDED",
  RECONCILIATION_PERIOD_CLOSED: "RECONCILIATION_PERIOD_CLOSED",
  RECONCILIATION_MATCH_NOT_FOUND: "RECONCILIATION_MATCH_NOT_FOUND",
  RECONCILIATION_REVERSE_NOT_ALLOWED: "RECONCILIATION_REVERSE_NOT_ALLOWED",

  // Identidade
  AUTH_INVALID_CURRENT_PASSWORD: "AUTH_INVALID_CURRENT_PASSWORD",

  // Genéricos
  NOT_FOUND: "NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  FORBIDDEN: "FORBIDDEN",
  UNAUTHENTICATED: "UNAUTHENTICATED",
} as const;

export type DomainErrorCode = (typeof DOMAIN_ERROR_CODES)[keyof typeof DOMAIN_ERROR_CODES];

/** Exceção de domínio com código estável, lançada pelos serviços de aplicação do backend. */
export class DomainError extends Error {
  readonly code: DomainErrorCode;
  readonly details?: Record<string, unknown>;

  constructor(code: DomainErrorCode, message: string, details?: Record<string, unknown>) {
    super(message);
    this.name = "DomainError";
    this.code = code;
    this.details = details;
  }
}
