'use client';

import { FormEvent, useEffect, useState } from 'react';

type Item = { id:string; code?:string; name:string; institutionName?:string; type?:string };
type Catalogs = { managementAccounts:Item[]; costCenters:Item[]; businessLines:Item[]; projects:Item[]; financialAccounts:Item[]; paymentTerms:Item[] };
type Supplier = { id:string; legalName:string; tradeName?:string };

const apiBase = process.env.NEXT_PUBLIC_API_URL ? `${process.env.NEXT_PUBLIC_API_URL}/api` : 'http://localhost:3001/api';

export default function NewPayablePage(){
  const today=new Date().toISOString().slice(0,10);
  const [legalEntityId,setLegalEntityId]=useState('');
  const [actorId,setActorId]=useState('');
  const [catalogs,setCatalogs]=useState<Catalogs|null>(null);
  const [suppliers,setSuppliers]=useState<Supplier[]>([]);
  const [message,setMessage]=useState('');
  const [error,setError]=useState('');
  const [form,setForm]=useState({supplierId:'',description:'',originalAmount:'',issueDate:today,competenceDate:today,dueDate:today,managementAccountId:'',costCenterId:'',businessLineId:'',projectId:'',costDirectness:'INDIRECT'});

  async function api<T>(path:string,init?:RequestInit){const r=await fetch(`${apiBase}${path}`,{...init,headers:{'Content-Type':'application/json',...(init?.headers||{})}});const b=await r.json();if(!r.ok)throw new Error(b?.message||'Falha na API');return b as T}
  async function load(){setError('');try{const [c,s]=await Promise.all([api<Catalogs>(`/financial/catalogs?legalEntityId=${legalEntityId}`),api<Supplier[]>(`/financial/suppliers?legalEntityId=${legalEntityId}`)]);setCatalogs(c);setSuppliers(s)}catch(e){setError(e instanceof Error?e.message:'Erro ao carregar catálogos')}}
  useEffect(()=>{if(legalEntityId)void load()},[legalEntityId]);

  async function submit(e:FormEvent){e.preventDefault();setError('');setMessage('');if(form.costDirectness==='DIRECT'&&(!form.businessLineId||!form.projectId)){setError('Custos diretos exigem linha de negócio e projeto.');return}try{await api('/financial/payables',{method:'POST',body:JSON.stringify({legalEntityId,supplierId:form.supplierId,description:form.description,competenceDate:form.competenceDate,issueDate:form.issueDate,originalAmount:form.originalAmount,currency:'BRL',sourceType:'MANUAL_ENTRY',createdBy:actorId,installments:[{dueDate:form.dueDate,amount:form.originalAmount}],allocations:[{managementAccountId:form.managementAccountId,costCenterId:form.costCenterId,businessLineId:form.businessLineId||undefined,projectId:form.projectId||undefined,amount:form.originalAmount,economicNature:'OPERATING_EXPENSE',costDirectness:form.costDirectness}]})});setMessage('Conta a pagar criada com sucesso.')}catch(e){setError(e instanceof Error?e.message:'Erro ao salvar')}
  }

  const Select=({label,value,onChange,items,required=true,disabled=false,placeholder='Selecione'}:{label:string;value:string;onChange:(v:string)=>void;items:Item[];required?:boolean;disabled?:boolean;placeholder?:string})=><label className="field"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)} required={required} disabled={disabled}><option value="">{placeholder}</option>{items.map(i=><option key={i.id} value={i.id}>{i.code?`${i.code} · `:''}{i.name}</option>)}</select></label>;

  return <main className="wrap"><header><div><p className="eyebrow">Financeiro · Contas a pagar</p><h1>Nova conta a pagar</h1><p className="muted">Classificação gerencial por nomes, sem copiar UUIDs.</p></div><a href="/">← Voltar ao workspace</a></header>
    <section className="env"><label>Legal Entity ID<input value={legalEntityId} onChange={e=>setLegalEntityId(e.target.value)} placeholder="temporário até autenticação"/></label><label>Actor/User ID<input value={actorId} onChange={e=>setActorId(e.target.value)} placeholder="temporário até autenticação"/></label><button type="button" onClick={load} disabled={!legalEntityId}>Atualizar catálogos</button></section>
    {error&&<div className="error">{error}</div>}{message&&<div className="success">{message}</div>}
    <form onSubmit={submit} className="card"><h2>Documento</h2><div className="grid"><label className="field full"><span>Fornecedor</span><select required value={form.supplierId} onChange={e=>setForm({...form,supplierId:e.target.value})}><option value="">Selecione</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.legalName}{s.tradeName?` · ${s.tradeName}`:''}</option>)}</select></label><label className="field full"><span>Descrição</span><input required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="field"><span>Valor</span><input required inputMode="decimal" value={form.originalAmount} onChange={e=>setForm({...form,originalAmount:e.target.value})}/></label><label className="field"><span>Emissão</span><input type="date" value={form.issueDate} onChange={e=>setForm({...form,issueDate:e.target.value})}/></label><label className="field"><span>Competência</span><input required type="date" value={form.competenceDate} onChange={e=>setForm({...form,competenceDate:e.target.value})}/></label><label className="field"><span>Vencimento</span><input required type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></label></div>
      <h2>Classificação gerencial</h2><div className="grid"><Select label="Conta gerencial" value={form.managementAccountId} onChange={v=>setForm({...form,managementAccountId:v})} items={catalogs?.managementAccounts||[]}/><Select label="Centro de custo" value={form.costCenterId} onChange={v=>setForm({...form,costCenterId:v})} items={catalogs?.costCenters||[]}/><label className="field"><span>Classificação</span><select value={form.costDirectness} onChange={e=>setForm({...form,costDirectness:e.target.value})}><option value="INDIRECT">Indireto</option><option value="DIRECT">Direto</option></select></label><Select label="Linha de negócio" required={form.costDirectness==='DIRECT'} value={form.businessLineId} onChange={v=>setForm({...form,businessLineId:v})} items={catalogs?.businessLines||[]}/><Select label="Projeto" required={form.costDirectness==='DIRECT'} value={form.projectId} onChange={v=>setForm({...form,projectId:v})} items={catalogs?.projects||[]} disabled={!catalogs?.projects.length} placeholder={catalogs?.projects.length?'Selecione':'Cadastro de projetos será o próximo módulo'}/></div>
      <div className="actions"><button className="primary" disabled={!catalogs}>Salvar conta a pagar</button></div></form>
    <style jsx>{`*{box-sizing:border-box}.wrap{max-width:1100px;margin:0 auto;padding:32px 20px 64px;color:#172033}header{display:flex;justify-content:space-between;gap:24px;align-items:flex-start;margin-bottom:24px}h1{font-size:32px;margin:4px 0}h2{font-size:18px;margin:24px 0 14px}.eyebrow{font-size:12px;text-transform:uppercase;letter-spacing:.12em;font-weight:700;color:#64748b}.muted{color:#64748b}.env,.card{border:1px solid #e2e8f0;border-radius:16px;background:#fff;padding:20px}.env{display:grid;grid-template-columns:1fr 1fr auto;gap:12px;align-items:end;margin-bottom:18px}.env label,.field{display:flex;flex-direction:column;gap:6px;font-size:13px;font-weight:600}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.full{grid-column:1/-1}input,select,button{min-height:44px;border:1px solid #cbd5e1;border-radius:9px;padding:10px 12px;font:inherit;background:#fff}select:disabled{background:#f1f5f9;color:#64748b}button{cursor:pointer;font-weight:700}.primary{background:#172033;color:white;border-color:#172033}.actions{display:flex;justify-content:flex-end;margin-top:24px}.error,.success{padding:12px 14px;border-radius:10px;margin-bottom:14px}.error{background:#fef2f2;color:#991b1b}.success{background:#f0fdf4;color:#166534}a{color:#334155;font-weight:700;text-decoration:none}@media(max-width:700px){header{flex-direction:column}.env,.grid{grid-template-columns:1fr}.full{grid-column:auto}}`}</style></main>
}
