export const SUPPLIER_INDUSTRIES = [
  'Automação e Integração de Sistemas',
  'Elétrica',
  'Instrumentação',
  'Painéis Elétricos e de Automação',
  'Mecânica e Caldeiraria',
  'Tubulação e Conexões',
  'HVAC e Climatização',
  'Telecomunicações, Redes e CFTV',
  'Segurança e Sistemas de Incêndio',
  'TI, Software e Licenciamento',
  'Materiais Elétricos',
  'Instrumentos e Equipamentos Industriais',
  'EPIs e Segurança do Trabalho',
  'Ferramentas e Consumíveis',
  'Usinagem e Fabricação Mecânica',
  'Serviços de Engenharia',
  'Construção Civil e Infraestrutura',
  'Logística e Transportes',
  'Locação de Equipamentos e Veículos',
  'Hospedagem, Viagens e Alimentação',
  'Contabilidade, Jurídico e Consultoria',
  'Outros',
] as const;
